ALTER TABLE games
    ADD COLUMN IF NOT EXISTS screenshots TEXT,
    ADD COLUMN IF NOT EXISTS background TEXT,
    ADD COLUMN IF NOT EXISTS website TEXT,
    ADD COLUMN IF NOT EXISTS metacritic INTEGER;
